# Generated by Django 2.2.6 on 2019-11-04 17:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homometer', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stat',
            name='avg',
        ),
        migrations.RemoveField(
            model_name='stat',
            name='max',
        ),
        migrations.RemoveField(
            model_name='stat',
            name='min',
        ),
    ]
